language: node_js
node_js:
  - 13

services:
- docker

#Pre-testing installs
install:
  -echo "nothing needs to be installed"

#Scripts to be run such as tests
before_script:
  - echo "no tests"

# Scrits being run
script:
  - sudo docker --version # give info on docker version
  - sudo docker build -t tax_app_oyf ./
  - sudo docker tag tax_app_oyf mfadhiligitau/tax_app1:latest

after_success: 
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push mfadhiligitau/tax_app1

